export const data = [
  {
    place: "mandi",
    temp: "30",
    weather: "cloudy",
    humidity: "60%",
    windSpeed: "12 km/h",
    pressure: "1012 hPa",
    visibility: "10 km",
    sunrise: "06:30 AM",
    sunset: "06:45 PM",
  },
  {
    place: "bilaspur",
    temp: "32",
    weather: "sunny",
    humidity: "55%",
    windSpeed: "10 km/h",
    pressure: "1010 hPa",
    visibility: "12 km",
    sunrise: "06:28 AM",
    sunset: "06:47 PM",
  },
  {
    place: "una",
    temp: "33",
    weather: "clear",
    humidity: "50%",
    windSpeed: "14 km/h",
    pressure: "1009 hPa",
    visibility: "11 km",
    sunrise: "06:27 AM",
    sunset: "06:48 PM",
  },
  {
    place: "kangra",
    temp: "29",
    weather: "rainy",
    humidity: "75%",
    windSpeed: "9 km/h",
    pressure: "1014 hPa",
    visibility: "8 km",
    sunrise: "06:31 AM",
    sunset: "06:44 PM",
  },
  {
    place: "shimla",
    temp: "22",
    weather: "foggy",
    humidity: "80%",
    windSpeed: "7 km/h",
    pressure: "1018 hPa",
    visibility: "6 km",
    sunrise: "06:35 AM",
    sunset: "06:40 PM",
  },

  {
    place: "chandigarh",
    temp: "34",
    weather: "sunny",
    humidity: "45%",
    windSpeed: "15 km/h",
    pressure: "1008 hPa",
    visibility: "13 km",
    sunrise: "06:20 AM",
    sunset: "06:55 PM",
  },
  {
    place: "delhi",
    temp: "36",
    weather: "hazy",
    humidity: "40%",
    windSpeed: "18 km/h",
    pressure: "1006 hPa",
    visibility: "7 km",
    sunrise: "06:15 AM",
    sunset: "07:00 PM",
  },
  {
    place: "jaipur",
    temp: "38",
    weather: "hot",
    humidity: "30%",
    windSpeed: "20 km/h",
    pressure: "1004 hPa",
    visibility: "14 km",
    sunrise: "06:10 AM",
    sunset: "07:05 PM",
  },
  {
    place: "mumbai",
    temp: "31",
    weather: "humid",
    humidity: "78%",
    windSpeed: "16 km/h",
    pressure: "1011 hPa",
    visibility: "9 km",
    sunrise: "06:05 AM",
    sunset: "06:55 PM",
  },
  {
    place: "pune",
    temp: "30",
    weather: "cloudy",
    humidity: "65%",
    windSpeed: "14 km/h",
    pressure: "1012 hPa",
    visibility: "10 km",
    sunrise: "06:07 AM",
    sunset: "06:57 PM",
  },

  {
    place: "bangalore",
    temp: "28",
    weather: "pleasant",
    humidity: "60%",
    windSpeed: "11 km/h",
    pressure: "1013 hPa",
    visibility: "12 km",
    sunrise: "06:00 AM",
    sunset: "06:40 PM",
  },
  {
    place: "chennai",
    temp: "34",
    weather: "humid",
    humidity: "75%",
    windSpeed: "17 km/h",
    pressure: "1009 hPa",
    visibility: "9 km",
    sunrise: "05:55 AM",
    sunset: "06:35 PM",
  },
  {
    place: "hyderabad",
    temp: "35",
    weather: "sunny",
    humidity: "50%",
    windSpeed: "13 km/h",
    pressure: "1007 hPa",
    visibility: "12 km",
    sunrise: "06:00 AM",
    sunset: "06:45 PM",
  },
  {
    place: "kolkata",
    temp: "33",
    weather: "humid",
    humidity: "70%",
    windSpeed: "12 km/h",
    pressure: "1010 hPa",
    visibility: "10 km",
    sunrise: "05:30 AM",
    sunset: "06:10 PM",
  },
  {
    place: "ahmedabad",
    temp: "37",
    weather: "hot",
    humidity: "35%",
    windSpeed: "19 km/h",
    pressure: "1005 hPa",
    visibility: "14 km",
    sunrise: "06:12 AM",
    sunset: "07:02 PM",
  },

  {
    place: "lucknow",
    temp: "35",
    weather: "cloudy",
    humidity: "55%",
    windSpeed: "14 km/h",
    pressure: "1008 hPa",
    visibility: "11 km",
    sunrise: "06:18 AM",
    sunset: "06:52 PM",
  },
  {
    place: "kanpur",
    temp: "36",
    weather: "sunny",
    humidity: "50%",
    windSpeed: "16 km/h",
    pressure: "1007 hPa",
    visibility: "12 km",
    sunrise: "06:17 AM",
    sunset: "06:53 PM",
  },
  {
    place: "bhopal",
    temp: "34",
    weather: "clear",
    humidity: "48%",
    windSpeed: "15 km/h",
    pressure: "1009 hPa",
    visibility: "13 km",
    sunrise: "06:14 AM",
    sunset: "06:58 PM",
  },
  {
    place: "indore",
    temp: "35",
    weather: "sunny",
    humidity: "42%",
    windSpeed: "17 km/h",
    pressure: "1008 hPa",
    visibility: "14 km",
    sunrise: "06:13 AM",
    sunset: "06:59 PM",
  },

  {
    place: "patna",
    temp: "34",
    weather: "cloudy",
    humidity: "65%",
    windSpeed: "12 km/h",
    pressure: "1011 hPa",
    visibility: "10 km",
    sunrise: "05:45 AM",
    sunset: "06:20 PM",
  },
  {
    place: "ranchi",
    temp: "32",
    weather: "rainy",
    humidity: "70%",
    windSpeed: "10 km/h",
    pressure: "1013 hPa",
    visibility: "8 km",
    sunrise: "05:50 AM",
    sunset: "06:25 PM",
  },
  {
    place: "guwahati",
    temp: "31",
    weather: "rainy",
    humidity: "80%",
    windSpeed: "9 km/h",
    pressure: "1014 hPa",
    visibility: "7 km",
    sunrise: "05:20 AM",
    sunset: "06:00 PM",
  },
  {
    place: "shillong",
    temp: "25",
    weather: "foggy",
    humidity: "85%",
    windSpeed: "6 km/h",
    pressure: "1016 hPa",
    visibility: "6 km",
    sunrise: "05:25 AM",
    sunset: "06:05 PM",
  },

  {
    place: "srinagar",
    temp: "24",
    weather: "pleasant",
    humidity: "55%",
    windSpeed: "8 km/h",
    pressure: "1017 hPa",
    visibility: "12 km",
    sunrise: "05:40 AM",
    sunset: "07:20 PM",
  },
  {
    place: "jammu",
    temp: "35",
    weather: "hot",
    humidity: "40%",
    windSpeed: "14 km/h",
    pressure: "1006 hPa",
    visibility: "13 km",
    sunrise: "05:50 AM",
    sunset: "07:10 PM",
  },
  {
    place: "leh",
    temp: "18",
    weather: "cold",
    humidity: "30%",
    windSpeed: "20 km/h",
    pressure: "1020 hPa",
    visibility: "15 km",
    sunrise: "05:35 AM",
    sunset: "07:30 PM",
  },
];
